name: Ariketa2
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Konposer
        run: composer install
      - name: phpunit
        run: vendor/bin/phpunit
